### ISSUE TITLE
Using Environmental Variables

### ISSUE THREAD

**Issue by UbiquitousBear** [preactjs/preact-cli#890] opened 2019-09-18 07:31 UTC
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Using `dotenv`, expose some environmental variables with a snippet in `preact.config.js` (below), additional environmental variables should be available via `process.env`.

Process is undefined.

**If the current behaviour is a bug, please provide the steps to reproduce.**

```
const { plugin } = helpers.getPluginsByName(config, 'DefinePlugin')[0];
const { parsed } = require('dotenv').config();
Object.assign(
  plugin.definitions,
  Object.keys(parsed).reduce(
    (env, key) => ({
      ...env,
      [`process.env.${key}`]: JSON.stringify(parsed[key]),
    }),
    {}
  )
);
```

package.json dependencies:

```
{
"devDependencies": {
        "@types/dompurify": "0.0.33",
        "@types/jest": "^23.3.10",
        "@types/node": "^12.7.5",
        "@types/prismjs": "^1.16.0",
        "@types/webpack-env": "^1.13.9",
        "css-loader": "^1.0.1",
        "dotenv": "^8.1.0",
        "husky": "^1.2.0",
        "identity-obj-proxy": "^3.0.0",
        "jest": "^23.6.0",
        "jest-preset-preact": "^1.0.0",
        "lint-staged": "^8.1.0",
        "per-env": "^1.0.2",
        "preact-cli": "^3.0.0-next.19",
        "prettier": "^1.15.3",
        "ts-jest": "^23.10.5",
        "ts-loader": "^3.5.0",
        "tslint": "^5.11.0",
        "tslint-config-prettier": "^1.17.0",
        "tslint-consistent-codestyle": "^1.14.1",
        "tslint-eslint-rules": "^5.4.0",
        "tslint-react": "^3.6.0",
        "typescript": "^3.2.1",
        "typings-for-css-modules-loader": "^1.7.0",
        "webpack": "^4.28.4"
    },
    "dependencies": {
        "@fortawesome/fontawesome-svg-core": "^1.2.22",
        "@fortawesome/free-regular-svg-icons": "^5.10.2",
        "@fortawesome/free-solid-svg-icons": "^5.10.2",
        "@fortawesome/react-fontawesome": "^0.1.4",
        "bootstrap": "^4.3.1",
        "dompurify": "^1.0.11",
        "marked": "^0.7.0",
        "preact": "^10.0.0-rc.1",
        "preact-render-to-string": "^5.0.6",
        "preact-router": "^3.0.1",
        "prismjs": "^1.17.1",
        "reactstrap": "^8.0.1",
        "webfontloader": "^1.6.28"
    }
}
```

**What is the expected behaviour?**

`process.env.VARIABLE_NAME` should be available

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.

```
        ▄▄
     ▄▄▓▓▓▓▓▓▄▄
  ▄█▀▀█▓▓▓▓▓▓▓▀▀█▄▄
▐▓▌▐▓▓▓▒▄ ▀▄▄▓▓▓▌▐▓▌
▐▓▓▄▀▓▀ ▄▓▓▄▄▀▓▓ ▓▓▌
▐▓▓▓▌ ▒▓▌  ▐▓▓  ▓▓▓▌ preact-cli 2.2.1
▐▓▓ ▒▓▄▄▀▓▓▀ ▄▓▓ ▓▓▌
▐▓▌▐▓▓▓▀▀▄▄▀▀▓▓▓▌▐▓▌
  ▀█▄▄▒▓▓▓▓▓▓▒▄▄▒▀
      ▀▓▓▓▓▓▓▀▀
         ▀▀
```

**Comment by bojan88** [comment] 2019-09-29 16:27
@UbiquitousBear I tried to reproduce the issue, but it seems like everything is working as expected.

I see that your package.json has one version, and you have another global version of `preact-cli` module. Maybe that can be the cause of your problems.

 I tried exposing variables from `.env` file using both `3.0.0-next.19` and `3.0.0-rc.5`, and everything looks fine.

**Comment by ahamedm** [comment] 2019-10-31 07:01
May be issue is because of per-env's limited support to yarn ?
https://github.com/ericclemmons/per-env/issues/16

`dotenv-webpack` should also work.

`
import Dotenv  from 'dotenv-webpack'
export default (config, env, helpers) => {    
    config.plugins.push(new Dotenv({path: "./.env"}));
  }
`

**Comment by ForsakenHarmony** [comment] 2019-10-31 15:12
@ahamedm that shouldn't be the issue because it's not in a `package.json` script?

**Comment by ahamedm** [comment] 2019-11-06 15:17
@ForsakenHarmony , 
I use yarn v1.17.3 instead of npm. I had the scripts in package.json as given below. But the environment variables referenced with `process.env.*` weren't resolved. Then I switched to `dotenv`
Now it works.

<pre>
  "scripts": {
-    "start": "per-env",
-    "start:production": "npm run -s serve",
-    "start:development": "npm run -s dev",
-    "build": "preact build",
-    "serve": "preact build && serve build --single",
-    "dev": "preact watch",
+    "start:development": "npx preact watch",
+    "start:production": "npx preact build && serve build --single",
     "lint": "eslint src",
-    "test": "jest"
+    "test:test": "jest"
   }
</pre>

**Comment by MarkPerry24** [comment] 2021-03-06 02:11
> @ForsakenHarmony ,
> I use yarn v1.17.3 instead of npm. I had the scripts in package.json as given below. But the environment variables referenced with `process.env.*` weren't resolved. Then I switched to `dotenv`
> Now it works.
> 
>   "scripts": {
> -    "start": "per-env",
> -    "start:production": "npm run -s serve",
> -    "start:development": "npm run -s dev",
> -    "build": "preact build",
> -    "serve": "preact build && serve build --single",
> -    "dev": "preact watch",
> +    "start:development": "npx preact watch",
> +    "start:production": "npx preact build && serve build --single",
>      "lint": "eslint src",
> -    "test": "jest"
> +    "test:test": "jest"
>    }

Am I missing something here?  The statement is "I use yarn" but the scripts use "npm run"  I thought mixing the two was probably not a good thing.  Choose apples or bananas rather than a bite from each.  

?

**Comment by rschristian** [comment] 2021-03-06 02:17
@MarkPerry24 If you look closely they're displaying a diff. '-' next to lines with 'npm', '+' to lines then using 'npx'. Not sure why they started using NPX, but Yarn doesn't really have an equivalent in any case.

There's no harm from mixing and matching, no. They operate slightly differently, so functionality may vary, but it's perfectly fine to do.

**Comment by MarkPerry24** [comment] 2021-03-06 02:30
> @MarkPerry24 If you look closely they're displaying a diff. '-' next to lines with 'npm', '+' to lines then using 'npx'. Not sure why they started using NPX, but Yarn doesn't really have an equivalent in any case.
> 
> There's no harm from mixing and matching, no. They operate slightly differently, so functionality may vary, but it's perfectly fine to do.

You're a star thank you.  I confess I'm  not well versed in js stuff and currently learning preact (I know react is de-facto but wanted to look at a different opinion).  I understand coding (lots of other lang) so have a jump on that bit.  My day job is infra and DevOps but trying to understand the how, what, if and why of js so that I can better support everyone.  Hopefully I'll nail js one-day but seems unlikely and js devs seem to like it that way that js is more than a little oily than other languages.

**Comment by rschristian** [comment] 2021-03-06 02:38
@MarkPerry24 I'm sure you'll get there. 

The environment may move a bit fast and can be a tad whacky at times but at the end of the day, like all languages, it's just a tool. Figure out which part you need when you need it and you'll be fine.

**Comment by ForsakenHarmony** [comment] 2021-03-06 15:13
I'll close this for now, given that it's working

**Closed by ForsakenHarmony** 2021-03-06 15:13 UTC
Labels: need more info
