### ISSUE TITLE
CSS opacity capped at 1% when using percentage units

### ISSUE THREAD

**Issue by jennydaman** [preactjs/preact-cli#1190] opened 2020-05-25 06:07 UTC
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behaviour?**

CSS `opacity` with units as a [percentage] is capped at `1%` for production builds.

**If the current behaviour is a bug, please provide the steps to reproduce.**

Minimal example:
https://github.com/jennydaman/opacity-onepercent-bug/commit/c98943de9f8b90df501f5a2690498d7f21d7ec5c

Repo above was created using `preact create --yarn --git default preact-opacity-bug`

![Screenshot](https://user-images.githubusercontent.com/20404439/82783123-e1f60300-9e2b-11ea-9aa7-105d94f5ab38.png)

```shell
yarn run build && yarn run serve
```

**What is the expected behaviour?**

`opacity: 67%` or whatever

**Please mention other relevant information.**

I think this might be a bug with webpack's `css-loader`, however I am unfamiliar with the code base (both preact-cli and css-loader). I'm hoping for a pointer on where this bug report should be made to or hints on how to trace/isolate the bug.

**Comment by RyanChristian4427** [comment] 2020-05-25 14:54
I have checked out the repository you've provided but the opacity seems to work correctly on my system. 

Have you tried deleting `node_modules` and your lock file, then reinstalling? You haven't pushed a lock file, so it's possible the versions of our dependencies are different, which causes you errors, but works for me.

**Comment by jennydaman** [comment] 2020-05-25 16:07
Oh sorry for that, I forgot to mention something important. This bug _only_ happens for production builds. I will edit my first comment....

```shell
yarn run build && yarn run serve
```

Also it seems like the lock file is included in `.gitignore` by default. You're right, isn't it a good practice to push the package lock file?
https://github.com/preactjs-templates/default/commit/f67ea78d66099fa237ebae769ba6b1848a0ea783#diff-0e2612bf56ebdfc6966ee7e8970361a9R1-R6

**Comment by RyanChristian4427** [comment] 2020-05-25 16:35
Thanks, that I can reproduce. 

It seems to be an issue only effecting CSS Modules. Importing the style sheet into the component works without issue. I'll try to take a look, see what might cause that. 

I don't know why the lock file is excluded by the `.gitignore` for that template, as none of the other templates have it ignored. Simple PR to fix though. Generally, yes, it is good practice to push. Yarn says it should always be pushed, NPM suggests that there are situations when it shouldn't, but none of those situations are web apps.

**Comment by jennydaman** [comment] 2020-05-25 16:41
PR for lockfile inclusion
https://github.com/preactjs-templates/default/pull/41

**Comment by jennydaman** [comment] 2020-05-25 16:46
minified CSS module is affected.

Inline style in JSX `style=opacity: 67%` is not affected.

This also means that inline styles are not minified (or at least are not processed the same way).

**Comment by RyanChristian4427** [comment] 2020-05-25 16:49
The bug stems from an issue with cssnano, which is used by optimize-css-assets-webpack-plugin. It's known and been fixed, just waiting on a new release. 

[Here's the PR in which it has been fixed](https://github.com/cssnano/cssnano/pull/881#issuecomment-627420821)

**Comment by prateekbh** [comment] 2020-05-26 17:47
so do we need to bumpsome of our dep and re-release?

**Comment by RyanChristian4427** [comment] 2020-05-26 18:34
> 
> 
> so do we need to bumpsome of our dep and re-release?

Well currently there's nothing to bump. The lib author just says a fix "will be released soon". The latest version was released a year ago, so "soon" is pretty vague. In the meantime, the author suggests using `postcss-ignore-plugin` to ignore it, or just disable the plugin outright. 

However, [opacity with percentages as units isn't even supported across the board by browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#Browser_compatibility), so there's always the possibility of ignoring this for a bit. Don't know how much effort anyone wants to put into fixing something that already won't work on a significant portion of the internet anyways.

**Comment by rschristian** [comment] 2022-12-22 07:57
Fixed with `cssnano` v5

**Closed by rschristian** 2022-12-22 07:57 UTC
Labels: upstream
