### ISSUE TITLE
the `typescript` template is broken out of the box

### ISSUE THREAD

**Issue by dartess** [preactjs/preact-cli#1698] opened 2022-05-29 11:55 UTC
**What is the current behaviour?**

After creating the project, it does not start.

**Steps to Reproduce**

1. `npx preact-cli create typescript preact`.
2. `cd preact`
3. `npm run dev`

```
ERROR in <...>/preact/tests/__mocks__/setupTests.ts(5,5):
TS2322: Type 'Adapter' is not assignable to type 'EnzymeAdapter'.
  The types returned by 'createElement(...)' are incompatible between these types.
    Type 'VNode<any>' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>'.
ERROR in <...>/preact/tests/header.test.tsx(8,33):
TS2769: No overload matches this call.
  Overload 1 of 3, '(node: ReactElement<any, string | JSXElementConstructor<any>>, options?: ShallowRendererProps | undefined): ShallowWrapper<...>', gave the following error.
    Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>>'.
      Types of property 'type' are incompatible.
        Type 'string | ComponentType<any>' is not assignable to type 'string | JSXElementConstructor<any>'.
          Type 'ComponentClass<any, {}>' is not assignable to type 'string | JSXElementConstructor<any>'.
            Type 'ComponentClass<any, {}>' is not assignable to type 'new (props: any) => Component<any, any, any>'.
              Construct signature return types 'Component<any, {}>' and 'Component<any, any, any>' are incompatible.
                The types returned by 'render(...)' are incompatible between these types.
                  Type 'ComponentChild' is not assignable to type 'ReactNode'.
                    Type 'bigint' is not assignable to type 'ReactNode'.
  Overload 2 of 3, '(node: ReactElement<any, string | JSXElementConstructor<any>>, options?: ShallowRendererProps | undefined): ShallowWrapper<...>', gave the following error.
    Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>>'.
  Overload 3 of 3, '(node: ReactElement<any, string | JSXElementConstructor<any>>, options?: ShallowRendererProps | undefined): ShallowWrapper<...>', gave the following error.
    Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any, string | JSXElementConstructor<any>>'.
```

**What is the expected behaviour?**

this should just work

```
Environment Info:
  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    preact: ^10.3.1 => 10.7.2 
    preact-cli: ^3.0.0 => 3.3.5 
    preact-render-to-string: ^5.1.4 => 5.2.0 
    preact-router: ^3.2.1 => 3.2.1 
```

**Comment by rschristian** [comment] 2022-05-29 18:54
Upstream types issue, duplicate of https://github.com/preactjs-templates/typescript/issues/71

**Closed** 2022-05-29 18:55 UTC
