### ISSUE TITLE
default project template doesn't work with Node v18

### ISSUE THREAD

**Issue by lhk** [preactjs/preact-cli#1773] opened 2023-01-12 12:23 UTC
**What is the current behaviour?**

The default project doesn't work with Node v18.

**Steps to Reproduce**
I'm following the [preactjs getting started guide]( https://preactjs.com/guide/v10/getting-started#best-practices-powered-by-preact-cli):
```
npx preact-cli create default my-project
cd my-project
npm install # this is not necessary I think
npm run dev
```
This code doesn't run. It results in the error message:
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
```

**What is the expected behaviour?**
It should be possible to use preactjs with an up-to-date version of Node, particularly when following the official tutorial.

**Please mention any other relevant information**
I think this issue is related: https://github.com/preactjs/preact-cli/issues/1579

Please paste the results of `npx preact-cli info` here.
```
Environment Info:
  System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 8.12.1 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 107.0
  npmPackages:
    preact: ^10.11.3 => 10.11.3 
    preact-cli: ^3.4.2 => 3.4.4 
    preact-render-to-string: ^5.2.6 => 5.2.6 
    preact-router: ^3.2.1 => 3.2.1 
```

**Comment by rschristian** [comment] 2023-01-12 14:42
Duplicate of #1643, #1748

**Closed** 2023-01-12 14:43 UTC
Labels: duplicate

**Comment by rschristian** [comment] 2023-01-13 17:11
Actually, 18 has very few (comparative) users; most people tend to only upgrade when necessary. I still see a fair number of 10 & 12 users on some projects I maintain.

But indeed, this isn't ideal. I'll try to think up a solution after work but it's a tad finicky as setting that env var can cause issues in a lot of systems, so we don't really want to do it ourselves.

As for the "Getting Started" instructions, [I've tried](https://github.com/preactjs/preact-www/pull/947). Can't do much more myself at this point.

**Comment by rschristian** [comment] 2023-01-14 18:36
Created #1774 for this.
