### ISSUE TITLE
preact-cli creates TypeScript app which fails its own pre-commit hook

### ISSUE THREAD

**Issue by mbrukman** [preactjs/preact-cli#1494] opened 2020-12-10 06:10 UTC
> **Do you want to request a _feature_ or report a _bug_?**

I think this is a bug, but I may very well be doing something wrong, so please let me know!

> **What is the current behaviour?**

Using the default installation instructions in the [docs](https://github.com/preactjs/preact-cli#usage), we get an initial TypeScript project template that works, but fails pre-commit hooks that it installs.

> **If the current behaviour is a bug, please provide the steps to reproduce.**

This is using preact-cli 3.0.5 (latest as of this writing).

```
$ cd ~
$ mkdir testing
$ cd testing
$ git init .   # needed to make sure the commit hook is installed
$ npx preact-cli create typescript ui
[lots of output]
✔  Done!
$ git add ui
$ git commit -v
husky > pre-commit (node v12.13.1)
⚠ Skipping backup because there’s no initial commit yet.

✔ Preparing...
⚠ Running tasks...
  ✔ Running tasks for *.{css,md,scss}
  ❯ eslint --fix [FAILED]
    ✖ eslint --fix [FAILED]
✔ Applying modifications...

✖ eslint --fix:
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

/Users/mbrukman/testing/ui/.eslintrc.js
  0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override

/Users/mbrukman/testing/ui/jest.config.js
  1:1  error  'module' is not defined  no-undef

/Users/mbrukman/testing/ui/preact.config.js
  13:21  warning  'env' is defined but never used      @typescript-eslint/no-unused-vars
  13:26  warning  'helpers' is defined but never used  @typescript-eslint/no-unused-vars
  13:35  warning  'options' is defined but never used  @typescript-eslint/no-unused-vars
  25:13  error    'process' is not defined             no-undef

/Users/mbrukman/testing/ui/src/components/app.tsx
  10:9   warning  'currentUrl' is assigned a value but never used  @typescript-eslint/no-unused-vars
  11:25  warning  Missing return type on function                  @typescript-eslint/explicit-function-return-type

/Users/mbrukman/testing/ui/src/components/header/style.css.d.ts
  3:22  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

/Users/mbrukman/testing/ui/src/routes/home/style.css.d.ts
  3:22  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

/Users/mbrukman/testing/ui/src/routes/notfound/style.css.d.ts
  3:22  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

/Users/mbrukman/testing/ui/src/routes/profile/index.tsx
  19:16  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type
  25:23  warning  Missing return type on function  @typescript-eslint/explicit-function-return-type

/Users/mbrukman/testing/ui/src/routes/profile/style.css.d.ts
  3:22  error  Interface name must not be prefixed with "I"  @typescript-eslint/interface-name-prefix

✖ 14 problems (6 errors, 8 warnings)

husky > pre-commit hook failed (add --no-verify to bypass)
```

> **What is the expected behaviour?**

I would expect the default template to cleanly pass the commit-hook. Alternatively, if that's not possible, it shouldn't install the commit-hook, because this means I have to force-disable it every time via `--no-verify` or go into the git config to delete the commit-hook.

> **If this is a feature request, what is motivation or use case for changing the behaviour?**

This is not a feature request.

> **Please mention other relevant information.**
>
> Please paste the results of `preact info` here.

I don't have `preact` installed as a global command since I'm using `npx preact-cli [...]` so:

```
$ npx preact-cli info
Environment Info:
  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  Binaries:
    Node: 15.3.0 - ~/bin/node
    Yarn: 1.22.10 - ~/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 83.0
    Safari: 13.1.2
```

**Comment by rschristian** [comment] 2020-12-10 08:22
Duplicate of https://github.com/preactjs-templates/typescript/issues/46 . Any template related issues can go over on the templates themselves. 

> because this means I have to force-disable it every time via --no-verify

You could also fix the linting issues. That's what's failing.

**Closed by rschristian** 2020-12-10 08:22 UTC

**Comment by mbrukman** [comment] 2020-12-23 17:47
Thanks, @rschristian!

> You could also fix the linting issues.

Since some of the files causing lint errors were generated files, it wasn't clear how to fix them: clearly modifying them isn't useful, but I wasn't sure where/how they're being generated from. Perhaps removing them from source control would fix it? I see what's what you're doing in https://github.com/preactjs-templates/typescript/pull/51, which makes sense.
