### ISSUE TITLE
"TypeError: Cannot read properties of undefined (reading 'call')" when trying to route split

### ISSUE THREAD

**Issue by PPHelios** [preactjs/preact-cli#1805] opened 2023-09-02 08:29 UTC
**What is the current behaviour?**
I have a react app and trying to migrate it to preact , I got to make most of the functionality's work but when trying to use code splitting it freezes at the prerendered page and logs an error `TypeError: Cannot read properties of undefined (reading 'call')`.

**Please mention any other relevant information**
Using normal import for the same file from a different folder works fine (included), and I'm not getting errors in both cases during dev or build.

From my understanding the splited routes are not prerendered but I tried to wrap every function calling browser api's with (typeof window !== "undefined") condition.

[route_splitting_issue.zip](https://github.com/preactjs/preact-cli/files/12503517/route_splitting_issue.zip)

1. I created a simplified project folder to focus on the issue.
2. kindly download it, extract.
3. run npm i
4. run npm build

Please paste the results of `npx preact-cli info` here.
Environment Info:
  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.203)
  npmPackages:
    preact: ^10.17.1 => 10.17.1
    preact-cli: ^4.0.0-next.1 => 4.0.0-next.2
    preact-render-to-string: ^5.2.6 => 5.2.6
    preact-router: ^4.1.2 => 4.1.2

**Comment by rschristian** [comment] 2023-09-02 22:30
I cannot reproduce from the provided repo. It seemingly builds just fine?

I should point out that your app breaks hooks; you cannot call hooks conditionally, in React or Preact. This is one of their intrinsic rules. Things like this will break your app:

```js
if (typeof window !== 'undefined') {
    mobile = useMediaQuery('(max-width: 520px)');
}
```

**Comment by PPHelios** [comment] 2023-09-03 11:04
I am very sorry @rschristian  I sent you wrong index.js file, I fixed it and removed all conditional hook calls even for translation to further simplify testing, but every thing works fine when not route importing, and in both cases no errors are produced during dev or build, it happens when I upload the static build to the host (hostinger), I will include tow links for both cases .

Route import: https://dev8.bdoonwasyt.com/
Normal import: https://dev9.bdoonwasyt.com/

thanks in advance!

**Comment by rschristian** [comment] 2023-09-03 11:08
Have you tested using the `serve` command locally? That will spin up a server to test the output of the `build` command.

There's nothing I can do to help you with that deployed site. I need source code.

**Comment by PPHelios** [comment] 2023-09-03 11:11
> Have you tested using the `serve` command locally? That will spin up a server to test the output of the `build` command.
> 
> There's nothing I can do to help you with that deployed site. I need source code.

[route_splitting_issue.zip](https://github.com/preactjs/preact-cli/files/12505802/route_splitting_issue.zip)

**Comment by rschristian** [comment] 2023-09-03 21:51
You still have conditional hooks:

```js
// routes/login/index.js

if (typeof window !== "undefined") {
    form = useForm({
      ...
    });
}
```

This fundamentally isn't allowed in React or Preact and it will completely break hooks in your app. You can read more [here](https://react.dev/learn/state-a-components-memory#how-does-react-know-which-state-to-return).

Your provided app does not build out-of-the-box, it's seemingly missing dependencies, and iss all of that `i18n` stuff needed? Those dependencies cause a dead-lock on the build process, something's not configured right.

**Comment by rschristian** [comment] 2023-09-03 21:55
I should also mention that you probably should look to use Vite, not Preact-CLI, for your Preact apps. We haven't been able to maintain this as much as we'd like and Webpack hasn't kept up well.

We have a Vite initializer which you can use by running `npm init preact`, it'll give you a few options before setting up your new project.

**Comment by rschristian** [comment] 2023-10-10 16:59
Closing, hopefully its been addressed.

**Closed by rschristian** 2023-10-10 16:59 UTC
