### ISSUE TITLE
build bundle.js only

### ISSUE THREAD

**Issue by fatlinesofcode** [preactjs/preact-cli#948] opened 2020-01-15 23:14 UTC
using the preact-cli build is it possible to build the bundle.js file only?

Currently I'm trying out the widget template and building using 
`
preact build --no-prerender --no-service-worker --template src/index.ejs
`

Then I'm seeing the following in the build folder
![Screen Shot 2020-01-16 at 10 10 06 am](https://user-images.githubusercontent.com/505776/72479464-a24d5800-3848-11ea-8438-2d40138573f6.png)

Ideally, I want to only output bundle.js + index.html as the other files are not used. If it possible to disable manifest.json, push-manifest.json, favicon and sw.js outputting?

**Comment by prateekbh** [comment] 2020-01-15 23:25
Given the project(preact-cli) is focussed on building `PWAs` primarily, I don't think that there is something that would get rid of all the files you are referring to.

But if for the `widget` template is makes sense to **ideally** just output those 2 files and other files are some sort of noise, then I would happily add a `post:build` script that would just delete the extra files.

**Comment by fatlinesofcode** [comment] 2020-01-15 23:45
maybe consdier a --no-pwa option @prateekbh ?

**Comment by prateekbh** [comment] 2020-01-15 23:48
The problem is that the term is super overloaded.

Does `--no-pwa` means
- delete manifest?
- delete SW?
- delete both?
because all of the above means its not a PWA.

Also that still leaves you with `push-manifest` and `favicon`. Do you think just deleting those files would be easier?

**Comment by fatlinesofcode** [comment] 2020-01-16 00:50
deleting files via a post build script would work fine for me @prateekbh 

But I think it would usefully to add something like a --bundle-only or --minimal flag which would only build the bundle.js and template for non-pwa apps

**Comment by alxvallejo** [comment] 2020-03-06 02:54
Hey use Preact and install with Preact-CLI - it's the smaller, lighter version of React! *Proceeds to generate ~20 bundle files that assume you're building a PWA*

**Comment by prateekbh** [comment] 2020-03-06 03:17
Does your app have 10ish routes?

**Comment by reznord** [comment] 2020-03-06 03:36
@alxvallejo you end up seeing ~20 bundle files because `preact-cli` publishes `.esm` bundles (for the latest browsers) and transpiled bundles (for the remaining browsers) by default.

Also, as your number of routes increases in the app, the number of bundle files also increases. What ever the subfolders you keep in `routes` folder, all those are considered as different chunks (i.e. route-based code splitting).

**Comment by alxvallejo** [comment] 2020-03-06 03:40
Ok then really quick question, if i want to just reference the dynamic bundle.xyz123,js file and embed Preact into a parent html file, how can I account for the dynamic `xyz123`?

**Comment by reznord** [comment] 2020-03-06 04:32
you can use a regex match like: `<link href="/bundle.w{5}.css" rel="preload" as="style">` for matching it with the bundle file.

**Comment by alxvallejo** [comment] 2020-03-06 14:30
@reznord Does html support regex? I've never seen that before and that gives me a 404 on this:
`http://localhost:8080/preact/build/bundle.w%7B5%7D.js ` \

?

**Comment by prateekbh** [comment] 2020-03-07 21:57
> Ok then really quick question, if i want to just reference the dynamic bundle.xyz123,js file and embed Preact into a parent html file, how can load what's in bundle.xYz.js?

What do you mean?
Like preact coming from some other previously bundled app and this one just load the route file? Like some sort of embedding just one page but in some other app?

**Comment by dungle-scrubs** [comment] 2020-12-17 03:56
I'm hoping to use Preact to build a widget over existing sites and would prefer to build everything into one .js file. 

With create-react-app, I am able to eject and modify the webpack config directly to make this happen, but not sure how to approach it with Preact.  

Any advice?

**Comment by rschristian** [comment] 2020-12-17 04:00
@dungle-scrubs 

The CLI has two widget templates for exactly this purpose.

**Comment by dungle-scrubs** [comment] 2020-12-17 04:08
> @dungle-scrubs
> 
> The CLI has two widget templates for exactly this purpose. [Widget](https://github.com/preactjs-templates/widget) and [TS-Widget](https://github.com/preactjs-templates/widget-typescript)
> 
> I believe I do have PRs open for both that overhaul them a fair bit. Might want to check those out first.

Awesome, appreciate it.

**Comment by dungle-scrubs** [comment] 2020-12-17 05:51
> @dungle-scrubs
> 
> The CLI has two widget templates for exactly this purpose. [Widget](https://github.com/preactjs-templates/widget) and [TS-Widget](https://github.com/preactjs-templates/widget-typescript)
> 
> I believe I do have PRs open for both that overhaul them a fair bit. Might want to check those out first.

Is there a way to use your unpublished PR #14 as a template via preact-cli?

**Comment by rschristian** [comment] 2020-12-17 05:55
> 
> Is there a way to use your unpublished PR #14 as a template via preact-cli?


Yep! You can either download from source (not recommended) or use Preact-CLI to initialize it:

```
npx preact-cli create rschristian/widget my-new-widget
```

**Comment by dungle-scrubs** [comment] 2020-12-17 06:07
works great, thank you

**Comment by dungle-scrubs** [comment] 2020-12-27 03:00
> Yep! You can either download from source (not recommended) or use Preact-CLI to initialize it:

What's the best way for me to give you feedback on your PR? Everything has gone super smooth up until `build` and `dist` are run.  I'm a little new to how PR's work and don't want to muddy up this thread.  Thanks!

**Comment by rschristian** [comment] 2020-12-27 03:05
@dungle-scrubs Are you on [the slack](https://chat.preactjs.com/)? Probably best for discussions. If that's the JS/widget template I know there's a few things I'm not a fan of myself at the moment, just lacking better solutions. Happy to try to help though.

**Comment by abdulimr** [comment] 2021-02-13 08:30
For anyone look at ways to remove the use of `manifest.json`, here's a simple postbuild script that does the job.

```js
/* postbuild.js */
const fs = require("fs")

const pages = [
  "/index.html",
  "/about/index.html",
  "/***/index.html",
  "200.html",
]

pages.forEach((page) =>
  fs.readFile(`build/${page}`, "utf8", (err, data) => {
    if (err) return console.log(err)

    const result = data.replace(
      '<link rel="manifest" href="/manifest.json">',
      ""
    )

    fs.writeFile(`build/${page}`, result, "utf8", (err) => {
      if (err) return console.log(err)
    })
  })
)
```

And the following script can be added to `package.json` to run it.

```js
"scripts":  {
    "postbuild": "node postbuild.js",
},
```
The postbuild script automatically runs after the build script.

Hope this helps someone out!

**Comment by rschristian** [comment] 2023-01-10 17:38
Going to close this out, this isn't going to be an officially supported thing.

You can maybe bend the Webpack config into shape via `preact.config.js`, but I'd probably discourage it.

**Closed by rschristian** 2023-01-10 17:38 UTC

**Comment by Defite** [comment] 2025-03-06 00:42
> > Is there a way to use your unpublished PR [#14](https://github.com/preactjs/preact-cli/pull/14) as a template via preact-cli?
> 
> Yep! You can either download from source (not recommended) or use Preact-CLI to initialize it:
> 
> ```
> npx preact-cli create rschristian/widget my-new-widget
> ```

As of March 2025 this is not working at all.

**Comment by rschristian** [comment] 2025-03-06 00:47
I think that should work just fine actually, though my fork was likely merged into the [preactjs-templates/widget](https://github.com/preactjs-templates/widget) many years ago. That's a 4+ year old comment at this point, not quite sure what you're expecting.

Regardless, preact-cli has long since been unmaintained and was never meant for this purpose. Look to other tools like [microbundle](https://github.com/developit/microbundle) which the widget template used anyhow.

**Comment by Defite** [comment] 2025-03-06 07:36
> I think that should work just fine actually, though my fork was likely merged into the [preactjs-templates/widget](https://github.com/preactjs-templates/widget) many years ago. That's a 4+ year old comment at this point, not quite sure what you're expecting.
> 
> Regardless, preact-cli has long since been unmaintained and was never meant for this purpose. Look to other tools like [microbundle](https://github.com/developit/microbundle) which the widget template used anyhow.

The thing is that the code I'm dealing with is 4 years old too. So I'm expecting those two work fine together) Thank you, sorry for bothering in closed issue.

**Comment by rschristian** [comment] 2025-03-06 07:41
Hm, well this issue is about adding an entirely new build config to CLI, a config that never existed. How old your code is wouldn't really matter as what this issue suggests (and what I'd still suggest today) is not using `preact-cli` to fulfill that use case -- it's not meant for it and would require a lot of hacking around the config for very little gain.

**Comment by Defite** [comment] 2025-03-06 07:45
> Hm, well this issue is about adding an entirely new build config to CLI, a config that never existed. How old your code is wouldn't really matter as what this issue suggests (and what I'd still suggest today) is not using `preact-cli` to fulfill that use case -- it's not meant for it and would require a lot of hacking around the config for very little gain.

Yeah, I understand this. Seems like there is also problem with my legacy dependencies, even if I use separate build config (I use webpack for this). But, this is the problem on my end, I got the concept, thank you!
