### ISSUE TITLE
Cannot run development server in Windows 10

### ISSUE THREAD

**Issue by gtbono** [preactjs/preact-cli#1062] opened 2020-03-22 01:40 UTC
I Installed a vanilla global preact-cli installation on Windows 10 2004 using Node.js v12.16.1.

npm install -g preact-cli

I used the following command to create a new preact app for my blog:

preact.cmd create default blog

And then I ran the following command to start a live server for development:

npm run start

At this moment, I expected that the server would show up, but instead, the following text is printed to my powershell console:

> blog@0.0.0 start C:\Users\gtbon\Code\blog
> per-env

And nothing happens, I'm unsure if this is a preact or preact-cli issue, I can open in preact-cli if needed.

**Comment by benhormann** [comment] 2020-03-27 17:52
You can use `npm run dev` to bypass per-env.

The problem is in the template: https://github.com/preactjs-templates/default/issues/36

**Comment by daniel-sudz** [comment] 2020-04-05 04:01
Same issue here #1115

**Comment by daniel-sudz** [comment] 2020-04-05 06:19
the solution by @benhormann has worked for me. Would it be possible to add this bypass to the preact-cli docs? I can submit a pull requested if this is wanted.

**Comment by ForsakenHarmony** [comment] 2020-04-06 11:45
We talked about briefly internally and think we can just remove `per-env` from all templates because it doesn't provide much value

If you want to make a PR, feel free

**Comment by gtbono** [comment] 2020-04-06 15:03
I can work in a PR for this

**Comment by ForsakenHarmony** [comment] 2020-04-06 20:55
Thanks for the PRs @daniel-sudz :tada:

**Comment by ForsakenHarmony** [comment] 2020-04-06 21:10
Should now be fixed in all templates

**Closed by ForsakenHarmony** 2020-04-06 21:10 UTC
