### ISSUE TITLE
Error launching dev server

### ISSUE THREAD

**Issue by txk64** [preactjs/preact-cli#1643] opened 2022-01-23 12:11 UTC
**What is the current behaviour?**
When trying to launch dev server I get this error message: `error:0308010C:digital envelope routines::unsupported`

**Steps to Reproduce**

1. Create a new app using the `simple` template.
2. Launch the dev server

**What is the expected behaviour?**
The dev server to launch

**Please mention any other relevant information**
I am running node 17 and this bug seems similar to [this](https://github.com/facebook/create-react-app/issues/11708) bug in `create-react-app`

Please paste the results of `npx preact-cli info` here.
```
Environment Info:
  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  Binaries:
    Node: 17.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.69)
  npmPackages:
    preact: ^10.1.0 => 10.6.4
    preact-cli: ^3.0.0 => 3.3.3
    preact-render-to-string: ^5.1.2 => 5.1.19
```

**Comment by txk64** [comment] 2022-01-23 13:46
Just a note for anyone else having this issue, a temporary workaround is to use the current LTS version of Node

**Comment by rschristian** [comment] 2022-01-23 17:42
Unfortunately it's a breaking change in Node that caused pretty widespread breakages across the ecosystem. See https://github.com/webpack/webpack/issues/14532

You'll need to set the `NODE_OPTIONS` env var to use the OpenSSL legacy provider, i.e.:

package.json
```json
{
  "scripts": {
    "dev": "NODE_OPTIONS=--openssl-legacy-provider preact watch"
  }
}
```

It doesn't look like Webpack v4 will ever get fixed, so this is required if you want to use v17+.

**Comment by txk64** [comment] 2022-01-29 13:20
Is there any plans to upgrade preact-cli to use Webpack 5?

**Comment by rschristian** [comment] 2022-01-29 18:48
Plans? Unfortunately no.

We'd like to upgrade, but we have limited maintainers with even more limited time; upgrading Webpack is always a very time consuming process. See https://github.com/preactjs/preact-cli/issues/1579

**Comment by rschristian** [comment] 2022-05-31 04:50
Closing this out as it's a duplicate of #1579 essentially.

Please track that for any further updates.

**Closed by rschristian** 2022-05-31 04:50 UTC
Labels: upstream, has-workaround
