### ISSUE TITLE
Typescript v5.1.6 compatibility

### ISSUE THREAD

**Issue by janmooij** [preactjs/preact-cli#1797] opened 2023-07-03 13:51 UTC
**What is the current behaviour?**
```
$ tsc
../../node_modules/preact/src/jsx.d.ts(1078,3): error TS2304: Cannot find name 'PictureInPictureEvent'.
../../node_modules/preact/src/jsx.d.ts(1124,3): error TS2344: Type 'TargetedPictureInPictureEvent<Target>' does not satisfy the constraint 'TargetedEvent<EventTarget, Event>'.
  Type 'TargetedPictureInPictureEvent<Target>' is missing the following properties from type 'Omit<Event, "currentTarget">': type, target, timeStamp, bubbles, and 17 more.
```

**Steps to Reproduce**

1. Create a preact project with typescript@v5.1.6
2. Try to build the project

**What is the expected behaviour?**
A succeeding build

**Please mention any other relevant information**
This started after upgrading `typescript` from `5.1.3` to `5.1.6`.  

Please paste the results of `npx preact-cli info` here.
```
Environment Info:
  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

**Comment by rschristian** [comment] 2023-07-03 20:03
I cannot reproduce, can you walk me through the exact steps / commands used please?

The reason for this is that `preact` itself now uses type definitions that are only bundled in newer releases of TypeScript. You're not seeing this error because of using a newer version of TypeScript, but quite the opposite in fact; it seems that you're running an older version without those newer type defs (likely caused by your package manager, not you, to be clear).

What you can try to do is use [`"overrides"`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides)/[`"resolutions"`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) in your `package.json` to specify the version of TypeScript that `preact-cli` should install (to `5.1.6`, or whatever you want). Something like this:

```json
"resolutions": {
    "preact-cli/typescript": "5.1.6"
}
```

This would force `preact-cli` to install a newer version of TypeScript to use, as (at the moment) it brings its own version along that it prioritizes.

We might be able to make TypeScript an optional peer dep, allowing users to bring in their own versions to avoid this completely, but I'll need a bit of time to test that out.

**Comment by rschristian** [comment] 2023-07-06 14:06
#1798 should've made this easier, so I'll close this out.

**Closed by rschristian** 2023-07-06 14:06 UTC
