### ISSUE TITLE
Choose output location of service worker generated by CLI

### ISSUE THREAD

**Issue by declanbyrd** [preactjs/preact-cli#1695] opened 2022-05-17 14:47 UTC
**What is the current behaviour?**
When a service worker is generated, the HTML assumes that the service worker will always be located at the web server's root.

**What is the motivation or use case for changing this behaviour?**
We have no control over the basic behaviour of our web server and our application is being served at `/my-cool-website/index.html`. At the moment we cannot register the service worker because our HTML assumes that the service worker is being served at `/` rather than `/my-cool-website/`.

**Describe the solution you'd like**
Set the destination path of the service worker in the preact-config so that when the Inject manifest plug-in is initialised that path can be passed into the constructor.

**Please mention any other relevant information.**

Please paste the results of `npx preact-cli info` here.

Environment Info:
  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 16.14.2 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/opt/node@16/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4

**Comment by declanbyrd** [comment] 2022-05-17 16:27
Sorry, you're right. By HTML I meant the output files produced by `preact build`. I have a public path set up exactly like the sample you have included above but this doesn't seem to affect the location of the service worker. In production it is still trying to request a service-worker.js file from the web server's root.

**Comment by rschristian** [comment] 2022-05-17 16:29
Have you removed the existing service worker manually through your dev tools? That might be your issue.

**Comment by declanbyrd** [comment] 2022-05-17 16:38
As far as I know, the issue occured in a new environment so no service workers had been registered previously.

**Comment by rschristian** [comment] 2022-05-17 16:45
Okay, we'll leave this open until then. I'd bet that this is the issue, as it's a very common one.

This is how we register the SWs, so as you can see, not much going on beyond Webpack substituting the publicPath in.

https://github.com/preactjs/preact-cli/blob/49bba048d3c33ab490b45009957d27f8014848c5/packages/cli/lib/lib/entry.js#L26-L29

**Comment by declanbyrd** [comment] 2022-05-18 08:55
Hi @rschristian, I had a look at un-registering the service workers but this doesn't seem to have resolved the issue. What I did find interesting was that our build files only contain `sw-esm.js` yet our application is requesting `sw.js`. We haven't changed the esm flag when running our build command so I'd assume it should be requesting `sw-esm.js`?

**Comment by rschristian** [comment] 2022-05-18 14:21
Your build files don't contain a `sw.js`? I don't think that's correct, no. But your ESM bundle should be requesting the `sw-esm.js`, yes.

Are you sure you unregistered the existing SW? In your browser's devTools, under "Application" (at least on Firefox)?

Try to disable cache and refresh, maybe you're caching incorrectly and using an outdated bundle? You can use your dev tools to check the `bundle.<hash>.esm.js`, just ctrl + f for 'sw.js' or 'sw-esm.js'.

How are you testing this by the way? With the local prod-like server (using `sirv` from our templates) or deploying your app to your prod env and testing that way?

**Comment by declanbyrd** [comment] 2022-05-18 14:42
> Are you sure you unregistered the existing SW? In your browser's devTools, under "Application" (at least on Firefox)?

I've tried this in Chrome and Firefox, neither had any existing service workers so there wasn't anything to unregister. On my colleague's machine, we unregistered an old service worker but this didn't seem to change anything either.

> Try to disable cache and refresh, maybe you're caching incorrectly and using an outdated bundle? You can use your dev tools to check the `bundle.<hash>.esm.js`, just ctrl + f for 'sw.js' or 'sw-esm.js'.

Disabling the cache and checking the first requested bundle shows this line `&&navigator.serviceWorker.register(n.p+"sw.js")`.

> How are you testing this by the way? With the local prod-like server (using `sirv` from our templates) or deploying your app to your prod env and testing that way?

We've been testing this in our production environment by deploying our static files to the web server. 

`Uncaught (in promise) TypeError: ServiceWorker script at https://192.168.50.30/my-cool-app/sw.js for scope https://192.168.50.30/my-cool-app/ encountered an error during installation. `

> Edit: A reproduction would help, if you could provide one.

I'm not able to provide an exact copy at the moment. I guess in its simplest form it's the typescript template with a preact.config.js that looks like this:

```js
import packageInfo from "./package.json";

module.exports = function (config, env, helpers) {
  config.output = config.output || {};
  if (process.env.NODE_ENV === "production") {
    config.output.publicPath = packageInfo.publicPath; // serve assets from sub-route
    config.devtool = false; // disable sourcemaps
    // ssr doesn't like us changing the file names so only run if not in ssr
    if (!env.ssr) {
      config.optimization.runtimeChunk = "single";
      config.output.chunkFilename = "[chunkhash].chunk.js";
      config.output.filename = "[contenthash].js";

      //Reduce file name length of css files.
      const { plugin: cssExtractPlugin } = helpers.getPluginsByName(
        config,
        "MiniCssExtractPlugin"
      )[0];
      cssExtractPlugin.options.moduleFilename = () => "[id].css";
      cssExtractPlugin.options.filename = "[id].css";
      cssExtractPlugin.options.chunkFilename = "[id].css";

      // Reduce file name length of esm js files.
      const babelEsmPlugin = helpers.getPluginsByName(
        config,
        "BabelEsmPlugin"
      )[0];
      if (babelEsmPlugin) {
        babelEsmPlugin.plugin.options_.chunkFilename =
          "[chunkhash].chunk.esm.js";
        babelEsmPlugin.plugin.options_.filename = "[contenthash].esm.js";
      }
    }
  }
}
```

**Comment by rschristian** [comment] 2022-05-18 16:29
> Disabling the cache and checking the first requested bundle shows this line &&navigator.serviceWorker.register(n.p+"sw.js").

Are you using a legacy browser? The ESM output will be used in every modern browser and it references `sw-esm.js` and that alone.

> What I did find interesting was that our build files only contain sw-esm.js yet our application is requesting sw.js. 

Cannot reproduce given the config you've provided. Both are output.

> `Uncaught (in promise) TypeError: ServiceWorker script at https://192.168.50.30/my-cool-app/sw.js for scope https://192.168.50.30/my-cool-app/ encountered an error during installation.`

What's the error?

Not much I can do without a reproduction or a way to observe the issue. I'd say try `sirv`, which all the templates ship with, and move on from there once you have your setup working. Faster iteration and you'll be able to better discern whether it's a deployment issue or build issue.

**Comment by rschristian** [comment] 2022-05-31 04:47
Going to close this out as without a reproduction of the issue and more information, there's nothing actionable.

We certainly can reopen this later if you can provide a reproduction.

**Closed by rschristian** 2022-05-31 04:47 UTC
Labels: need more info
