### ISSUE TITLE
force does not work

### ISSUE THREAD

**Issue by HawkeyePierce89** [preactjs/preact-cli#905] opened 2019-10-16 12:58 UTC
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behaviour?**

preact-cli does not create project for exist folder. Or, put it another way, `force` option does not work.

I have screenshot with erroneous behavior

![exist](https://user-images.githubusercontent.com/25603805/66920776-ab057680-f02c-11e9-9c0f-a87db1565fc9.png)

If I create project to nonexistent folder all works correctly

![new](https://user-images.githubusercontent.com/25603805/66921112-3a128e80-f02d-11e9-90ca-105f85c1065b.png)

**What is the expected behaviour?**

`force` option should work correctly and create project in my exist folder.

I am using Windows 10 Enterprise build 18362.

**Comment by bojan88** [comment] 2019-12-28 19:13
I've tested this on Linux, node v13.3.0.
Everything worked fine.
It might not be possible to reproduce on Linux.

Here's my `preact info`:
```
Environment Info:

  System:
    OS: Linux 5.4 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    npm: 6.7.0 - ~/.npm-global/bin/npm
  Browsers:
    Firefox: 71.0
  npmGlobalPackages:
    preact-cli: 3.0.0-rc.5
```

@HawkeyePierce89 can you please share your output from `preact info`?

**Comment by rschristian** [comment] 2022-12-22 08:09
I can't reproduce either.

Might've gotten fixed at some point. Closing out.

**Closed by rschristian** 2022-12-22 08:09 UTC
