### ISSUE TITLE
Async component mounted/shown twice at same time

### ISSUE THREAD

**Issue by shalomvolchok** [preactjs/preact-cli#677] opened 2018-12-01 19:28 UTC
I've been working with the `preact-cli` material template and it seems that a call to `setState` from within `handleRoute` of [`app.js`](https://github.com/preactjs-templates/material/blob/master/template/src/components/app.js#L17) causes the async wrapper's [`componentWillMount`](https://github.com/developit/preact-cli/blob/next/packages/async-loader/async.js#L8) to fire twice, resulting in the async component being duplicated on the screen.  (next branch 3.0.0-next.14, but also observed in v2).

This behavior can be seen with `npm run serve` after running `preact-cli create material demo`, but the page needs to be scrolled to notice the duplication (I didn’t notice for some time).

I also have a stripped down repo that minimally reproduces the behavior (without the router nor material design): https://github.com/shalomvolchok/async-route-duplication

In the stripped down repo the behavior is triggered by calling `setState` from `componentDidMount` (in any component higher than the async component).

I had to dig for a while before I figured out where the double rendering was coming from, but it’s still not clear to me what the right solution would be to avoid/fix this. What do you all think?

**Comment by prateekbh** [comment] 2018-12-04 21:19
cc @developit i am not sure if this should be fixed in the template or the `async wrapper`

**Comment by jjperezaguinaga** [comment] 2018-12-09 18:21
Just to mention that I'm facing the same issue, going to poke around to see what are the best steps to avoid this.

**Comment by shalomvolchok** [comment] 2018-12-09 18:43
A quick temporary hack

```js
setTimeout(()=>{this.setState({/*...*/}},0)
```

**Comment by prateekbh** [comment] 2018-12-11 03:53
I personally don't think we should be doing this hack, @developit can u check?

**Comment by prateekbh** [comment] 2018-12-11 03:54
cc: @lukeed

**Comment by developit** [comment] 2019-01-03 23:16
the bit that causes the duplication is pretty important, it prevents the first client-side render from ripping out the prerendered DOM. Looks like we just need to synchronously flush via forceUpdate instead of setState.

**Comment by jjperezaguinaga** [comment] 2019-02-01 05:39
👋 just wanted to share that sadly the hack isn't really working as I thought, and keep getting the issue whenever I prerender it with `preact build`. Any suggestion on how to be able to serve a `preact-cli` app statically without having the same component twice.

**Comment by jjperezaguinaga** [comment] 2019-04-08 17:31
@developit @ForsakenHarmony could I get more information on what do you think it's causing the issue here or some pointers on where to look? Maybe I can do some work on my own to solve this, as my current site still has this issue and haven't been able to work around it 😢

**Comment by pragmatech** [comment] 2019-04-12 08:15
My preact-cli material template on Netlify renders duplicate divs as well. The said hack sort of ameliorated this on chrome -- not firefox. Is ditching the material goodies the best way to proceed at this point?

**Comment by ForsakenHarmony** [comment] 2019-04-13 09:34
The problem is or async component, more specifically the `dangerousSetInnerHtml`

It's a workaround for a flash of no content

Not sure why it would happen for prerendering though

**Comment by lucie-macikova** [comment] 2019-05-27 20:11
Hi, any update on this? 
The hack is not really working and at the moment which means the production build can't be published. 

Is there any way around this? And I mean anything that would allow me to publish this even if that has some downsides?

**Comment by ForsakenHarmony** [comment] 2019-05-27 20:53
well you can rename `routes` to anything else and it won't auto async it

**Comment by mfbx9da4** [comment] 2019-06-16 09:08
Can you give an example how to do this @ForsakenHarmony ? The hack is also not working for me. I'm happy to abandon code splitting. What would be the best way to do that?

**Comment by TheNando** [comment] 2019-07-02 02:55
I ended up just turning off pre-rendering in my build until this is resolved. Not ideal, but it is better than the dupe.
```
// In package.json
  "build": "preact build --no-prerender",
`

**Comment by prateekbh** [comment] 2019-07-02 20:28
@developit has a Suspense based fix for this.
Will wait for his PR

**Comment by developit** [comment] 2019-08-05 01:55
The confusing part is that folks are seeing this in Preact 8. My fix is specific to Preact X.

**Comment by Pierre-Gilles** [comment] 2020-02-28 11:08
I'm on Preact X and I think I have the same problem (not sure)

When I develop, after a few changes, my routes are duplicated (all of them). Just force-refreshing the page fix it

<img width="1440" alt="Screenshot 2020-02-28 at 12 05 53" src="https://user-images.githubusercontent.com/7365207/75543698-b6c56880-5a22-11ea-850d-5ba602861b4f.png">

<img width="1440" alt="Screenshot 2020-02-28 at 12 05 40" src="https://user-images.githubusercontent.com/7365207/75543812-f2603280-5a22-11ea-866c-b46eadaf88e3.png">

**Comment by ForsakenHarmony** [comment] 2020-02-28 13:39
@Pierre-Gilles `preact-cli` v2 is not really compatible with `preact` v10

But we still haven't gotten code splitting to work for preact 10 in cli@rc

**Comment by Pierre-Gilles** [comment] 2020-03-02 08:52
@ForsakenHarmony Oh I didn't know, thanks !

Any idea of a fix while waiting for `preact-cli` v3 ?

**Comment by ForsakenHarmony** [comment] 2020-03-03 23:13
cli@rc should be usable in it's current form, if you don't need async loading it could work for you

**Closed** 2020-06-29 16:32 UTC
Labels: bug
