### ISSUE TITLE
Prerendered routes' css is not being inlined in TS config

### ISSUE THREAD

**Issue by prateekbh** [preactjs/preact-cli#1393] opened 2020-08-31 16:16 UTC
see https://github.com/preactjs-templates/typescript/issues/42#issuecomment-683313136

**Comment by rschristian** [comment] 2020-11-12 00:09
Should be fixed now, can't reproduce on v3.0.3. I believe this is due #1413. 

Cause was found here: https://github.com/preactjs/preact-cli/issues/1470#issuecomment-725275691. In the past the CLI used to generate `route-home/index.[jsx,css]`. This was a problem as Critters was only set to check top-level files https://github.com/preactjs/preact-cli/blob/4cc93bac3e209c33913b2cf2fc711d45c1bd86df/packages/cli/lib/lib/webpack/webpack-client-config.js#L261.

With the route directories no longer being generated in the output folder Critters should be working again.

**Closed** 2020-11-12 18:05 UTC
