### ISSUE TITLE
preact-cli hangs after "✔ Done!"

### ISSUE THREAD

**Issue by ristiisa** [preactjs/preact-cli#1792] opened 2023-06-16 06:58 UTC
`npx preact-cli create default app2` hangs a minute or so after "✔ Done!"

Would be nice if there would a message in the lines of "please wait doing something"

```
node v19.7.0
windows 10
preact 3.4.5
```

**Comment by rschristian** [comment] 2023-06-16 10:27
Hmm, well nothing is actually being done after that message is output. Some getting started instructions should be printed out right afterwards, but that's (more or less) just a `console.log()`.

I can't reproduce, but I don't have access to a Windows machine myself. Don't know what could be going wrong there.

**Comment by ristiisa** [comment] 2023-06-17 08:19
any debugging hints?

**Comment by rschristian** [comment] 2023-06-17 08:25
Unfortunately, not really. My only real guess is that it's [`ora`](https://npm.im/ora), the spinner we use, not exiting correctly.

Here's the [relevant source code](https://github.com/preactjs/preact-cli/blob/master/packages/cli/src/commands/create.js#L372-L394). As you can see, nothing is actually done after that message (the git flag defaults to `false`).

Really weird. Is that a consistent issue?

**Comment by ristiisa** [comment] 2023-06-17 08:27
Yeah, happens every time. I'll try different terminals, perhaps there is something there

**Comment by rschristian** [comment] 2023-08-15 05:47
Going to close this out as I haven't been able to reproduce the issue.

**Closed by rschristian** 2023-08-15 05:47 UTC
