### ISSUE TITLE
SCSS sourcemaps are included in the build of preactjs-templates/widget

### ISSUE THREAD

**Issue by Markovnin** [preactjs/preact-cli#899] opened 2019-10-02 05:59 UTC
By default, `npm run build` will leave SCSS source maps in the build code (see attached image). Is there a way to disabled it? Source maps are not needed in the build.

<img width="941" alt="0gSkK" src="https://user-images.githubusercontent.com/37826/65957134-c7ae8580-e454-11e9-815e-08795cabb7a7.png">

**Comment by rschristian** [comment] 2022-12-23 02:17
Closing this out, cannot reproduce anymore.

Likely an issue with the old build process.

**Closed by rschristian** 2022-12-23 02:17 UTC
