### ISSUE TITLE
Linter configuration errors (typescript template)

### ISSUE THREAD

**Issue by obasille** [preactjs/preact-cli#1712] opened 2022-07-15 11:16 UTC
**What is the current behaviour?**
Linter failing to run.

**Steps to Reproduce**

```sh
npx preact-cli create typescript myproject
cd myproject
npm i
npm run lint
```

I'm getting:

> Oops! Something went wrong! :(
> 
> ESLint: 6.8.0.
> 
> No files matching the pattern "'src/**/*.{js,jsx,ts,tsx}'" were found.

But then, running "eslint ." gives another error:

> 
> Oops! Something went wrong! :(
> 
> ESLint: 6.8.0.
> 
> ESLint couldn't find the plugin "eslint-plugin-jest".

Both installing the latest `eslint-plugin-jest` or version 25.7.0 (which is the one I got inside eslint-config-preact) fail because of dependency conflicts.

Thanks for your help!

**Please mention any other relevant information**

```
Environment Info:
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
  npmPackages:
    preact: ^10.3.1 => 10.10.0
    preact-cli: ^3.0.0 => 3.4.0
    preact-render-to-string: ^5.1.4 => 5.2.1
    preact-router: ^3.2.1 => 3.2.1
```

**Comment by rschristian** [comment] 2022-07-15 19:40
> I'm getting:
>
>>    Oops! Something went wrong! :(
>>
>>    ESLint: 6.8.0.
>>
>>    No files matching the pattern "'src/**/*.{js,jsx,ts,tsx}'" were found.

Hm, odd. There most certainly are files matching that pattern, and I can't reproduce.

> But then, running "eslint ." gives another error:
>
>>    Oops! Something went wrong! :(
>>
>>    ESLint: 6.8.0.
>>
>>    ESLint couldn't find the plugin "eslint-plugin-jest".

Duplicate of https://github.com/preactjs-templates/typescript/issues/67

I have no idea what causes this, as `eslint-pluin-jest` is labeled as a dependency of the preact config. Why this only happens for that specific dependency is beyond me.

**Comment by obasille** [comment] 2022-07-16 11:18
That’s interesting that you can’t reproduce that issue. Are you on Windows too? As a comparison I’ll try on a Mac next week.

On 15 Jul 2022, at 21:40, Ryan Christian ***@***.***> wrote:

﻿

I'm getting:

Oops! Something went wrong! :(

ESLint: 6.8.0.

No files matching the pattern "'src/**/*.{js,jsx,ts,tsx}'" were found.

Hm, odd. There most certainly are files matching that pattern, and I can't reproduce.

But then, running "eslint ." gives another error:

Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the plugin "eslint-plugin-jest".

Duplicate of preactjs-templates/typescript#67<https://github.com/preactjs-templates/typescript/issues/67>

I have no idea what causes this, as eslint-pluin-jest is labeled as a dependency of the preact config. Why this only happens for that specific dependency is beyond me.

**Comment by rschristian** [comment] 2022-07-16 11:25
No, Linux.

Regardless, there's nothing actionable here for `preact-cli`, so I'm going to close this out. If you ever track down the problem you can open an issue on the template(s), the ESLint config, ESLint or NPM themselves, wherever it fits.

All I can do at the moment is point out the file patterns are correct and the eslint config does list the jest plugin as a dependency.

**Closed** 2022-07-16 11:25 UTC

**Comment by rschristian** [comment] 2022-07-18 12:43
Ugh, goddamit Windows.

Thanks! I'll try to push out that fix to the templates later today.

That peer dep issue (which I see now, thanks!) is rather annoying. Really don't want to have to continually update the templates just to satisfy a linter of all things, though might just be able to rip out `@typescript-eslint/eslint-plugin` and let the Jest plugin install whatever version it needs.

Will have to consider ripping out ESLint entirely and leaving it up to users to configure as they wish.

**Comment by obasille** [comment] 2022-07-19 07:16
Just tried it and it works like a charm, thank you @rschristian!

**Comment by rschristian** [comment] 2022-07-19 07:17
Yay! Thanks so much for tracking those issues down!
