### ISSUE TITLE
HMR not working with custom folder structure

### ISSUE THREAD

**Issue by srobertson421** [preactjs/preact-cli#685] opened 2018-12-15 20:42 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behaviour?**
When running either `npm start` or `npm run dev` from within a `default` template preact project, HMR starts up and dev server renders the app once, but subsequent changes to components don't show up. HMR message in the console is:

```
[HMR] Waiting for update signal from WDS...
```

No errors in the terminal.

My typical folder structure is:

```
src/
---- assets/
---- components/
-------- layout/
------------ Column.js
------------ Container.js
------------ index.js
---- routes/
-------- Home/
------------ Home.js
------------ HomeStyles.css
------------ index.js
---- style
---- App.js
---- index.js
```

I use the `index.js` file in routes/components folder to allow for clearer file names. index files typically import the component and export it as a default so that I only have to reference the outer directory to import the components elsewhere.

Not sure if this is frowned upon with preact-cli, or if it's a webpack issue.

**If the current behaviour is a bug, please provide the steps to reproduce.**
- run `preact create default <template-name>`
- run `cd <template-name> && npm start`
- navigate browser to `http://localhost:8080`
- open JS console to see message
- Try editing code to see if app updates

**What is the expected behaviour?**
HMR should trigger on changes and update rendered Preact application in browser.

**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**
- Node version
- npm version
- Operating system
- CLI version
- Browser

Using:
OS: macOS
Browser: Chrome Version 70.0.3538.110
Editor: Atom
Shell: iTerm 2
Preact-CLI: 2.2.1
Node: v11.4
NPM: 6.4.1

**Comment by reznord** [comment] 2019-02-07 06:23
@srobertson421 can you confirm if the issue still persists? Because I just tried to replicate this issue and am not able to reproduce.

**Comment by bojan88** [comment] 2019-04-24 15:21
I can confirm this issue with preact-cli version 3.0.0-next.19.
There's an error displayed quickly before the page reloads.

![hmr_errors](https://user-images.githubusercontent.com/1783133/56671680-0f99d700-6683-11e9-8708-fec7c53c8572.png)

**Comment by ForsakenHarmony** [comment] 2019-06-29 21:39
Seems like a webpack issue?

**Comment by reznord** [comment] 2020-03-21 07:11
Seems like this is fixed in the latest versions of CLI. Feel free to re-open if the issue persists.

**Closed by reznord** 2020-03-21 07:11 UTC
Labels: feedback needed, upstream
